networks:
  inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/wordpress'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - 3306
  wordpress:
    build: requirements/wordpress/
    image: wordpress
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    env_file: .env
  nginx:
    build: requirements/nginx/
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    extra_hosts:
      - "egeorgel.42.fr:127.0.0.1"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    restart: always